version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
      sh -c "python worker.py"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
      - neo4j
  worker:
    build: .
    command: >
      sh -c "python worker.py"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - neo4j
      - app

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    env_file:
      - .env
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # BOLT
    env_file:
      - .env